[project]
name = "swartech-admin-panel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "firebase>=4.0.1",
    "firebase-admin>=7.1.0",
    "pydantic>=2.11.9",
    "uvicorn>=0.37.0",
]
